/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IMemberContract,
  IMemberContractInterface,
} from "../../ProjectSubmission.sol/IMemberContract";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "isMember",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IMemberContract__factory {
  static readonly abi = _abi;
  static createInterface(): IMemberContractInterface {
    return new Interface(_abi) as IMemberContractInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IMemberContract {
    return new Contract(address, _abi, runner) as unknown as IMemberContract;
  }
}
