/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { IVote, IVoteInterface } from "../../InfraDAO.sol/IVote";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "index",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "votes",
        type: "uint256",
      },
    ],
    name: "projectVote",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IVote__factory {
  static readonly abi = _abi;
  static createInterface(): IVoteInterface {
    return new Interface(_abi) as IVoteInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IVote {
    return new Contract(address, _abi, runner) as unknown as IVote;
  }
}
