/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "HederaTokenService",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.HederaTokenService__factory>;
    getContractFactory(
      name: "IHederaTokenService",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IHederaTokenService__factory>;
    getContractFactory(
      name: "InfraDAO",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.InfraDAO__factory>;
    getContractFactory(
      name: "IVote",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IVote__factory>;
    getContractFactory(
      name: "IMemberContract",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IMemberContract__factory>;
    getContractFactory(
      name: "ProjectSubmission",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ProjectSubmission__factory>;
    getContractFactory(
      name: "ProjectTokenAssociate",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ProjectTokenAssociate__factory>;

    getContractAt(
      name: "HederaTokenService",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.HederaTokenService>;
    getContractAt(
      name: "IHederaTokenService",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IHederaTokenService>;
    getContractAt(
      name: "InfraDAO",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.InfraDAO>;
    getContractAt(
      name: "IVote",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IVote>;
    getContractAt(
      name: "IMemberContract",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IMemberContract>;
    getContractAt(
      name: "ProjectSubmission",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ProjectSubmission>;
    getContractAt(
      name: "ProjectTokenAssociate",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ProjectTokenAssociate>;

    deployContract(
      name: "HederaTokenService",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.HederaTokenService>;
    deployContract(
      name: "IHederaTokenService",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IHederaTokenService>;
    deployContract(
      name: "InfraDAO",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.InfraDAO>;
    deployContract(
      name: "IVote",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IVote>;
    deployContract(
      name: "IMemberContract",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IMemberContract>;
    deployContract(
      name: "ProjectSubmission",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ProjectSubmission>;
    deployContract(
      name: "ProjectTokenAssociate",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ProjectTokenAssociate>;

    deployContract(
      name: "HederaTokenService",
      args: any[],
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.HederaTokenService>;
    deployContract(
      name: "IHederaTokenService",
      args: any[],
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IHederaTokenService>;
    deployContract(
      name: "InfraDAO",
      args: any[],
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.InfraDAO>;
    deployContract(
      name: "IVote",
      args: any[],
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IVote>;
    deployContract(
      name: "IMemberContract",
      args: any[],
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IMemberContract>;
    deployContract(
      name: "ProjectSubmission",
      args: any[],
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ProjectSubmission>;
    deployContract(
      name: "ProjectTokenAssociate",
      args: any[],
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ProjectTokenAssociate>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.Contract>;
  }
}
